# Generated by Django 5.1.6 on 2025-02-25 17:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('price', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Price')),
                ('stock_house', models.PositiveIntegerField(default=1, verbose_name='StockHouse')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
